---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking

helmCharts:
  - name: pihole
    releaseName: pihole
    namespace: networking
    repo: https://github.com/MoJo2600/pihole-kubernetes
    version: pihole-2.11.1
    valuesFile: values.yaml