global:
  enabled: false
metrics:
  enabled: true
service:
  enabled: true
server:
  updateStrategyType: RollingUpdate
  enabled: true
#  dataStorage:
#    enabled: true
#    size: 5Gi
#    storageClass: local-path
#  auditStorage:
#    enabled: true
#    size: 5Gi
#    storageClass: local-path
  logFormat: "json"
  ingress:
      enabled: false
  readinessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
    standalone:
      enabled: true
      config: |
        log_format = "json"
        log_level = "debug"
        ui = true
        cluster_name = "home-k3s"
        storage "file" {
          path = "/vault/data"
        }
        # HTTPS listener
        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_disable = 1
        }
        telemetry {
          prometheus_retention_time = "24h"
          disable_hostname = true
        }