---
apiVersion: v1
kind: ConfigMap
data:
  resource.exclusions: |
     - apiGroups:
         - cilium.io
       kinds:
         - CiliumIdentity
       clusters:
         - "*"
  kustomize.buildOptions: --enable-alpha-plugins --enable-helm
  url: https://argocd.abasitt.tech
  oidc.config: |
    name: Keycloak
    issuer: https://auth.dagobah.abasitt.tech/auth/realms/home-prod
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm