# can add to the overlay patch cuz it will be sops encrypted. just manually edit the argocd-secret in the cluster.
apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
data:
    oidc.keycloak.clientSecret: ENC[AES256_GCM,data:ZsBKzk+BkZYr1x6JC3Gwt75F+oXMdN/BD0HMLPZzpK/QjF2H7byy1BulruY=,iv:+QzozrpT10AldBWCl6s+yLEyLnOYzxQEvbE5tYn4w6Q=,tag:SbR5nKiKc0sRLBtta4QIRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyb2VIZ2xhRlFkd3lQV2dm
            MHVyYm8xcExadUI5a0tzcnlPNXBBNDZOeXdRCnVwOVIzd29wT1JlWFV4RjFXREVr
            VTBTT1k3eVU5NVFrNFdkRGdYeW9UUzgKLS0tIFBua3FqS3NaQUkxM2JMRW9hbW5s
            eDZicnM5cEE5TmV3TjZRTzVqSklEWUEKjaRC+Tzo2kffobChZ2LQJGsUEjc9KkxU
            VYSwUpF00wPgf3By2+LSEB8jub63/ilGIfkJauVI9qlhf79spd3XTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-14T14:03:21Z"
    mac: ENC[AES256_GCM,data:m/WIA1vW5mIxWGsIIEw+uKsxOdEQFAAQNo0Ls2xiOvpibC0T59fC/Vj7AjKcerCsucpfKG4i9lN8YLzPngpsF8QkFzgDPJn1NgtAzPwlIkNkPw3F8njZLUCXjarY9GCvZoMcTD7PztnN5JS89mM36Xj1DpH18dIVUo+AcAOnY1Q=,iv:qWuGwq79FbyJ20waKZuWE+kl2tKkgg6jZ1dG4ralBS0=,tag:NR6JjFsfj4qdodsdOSneXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
