---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-originals-pvc
  namespace: media
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: manual
  resources:
    requests:
      storage: 300Gi