---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-originals-pv
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 300Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nfs.hv01.home.arpa
    path: /zp_sda_sdb/k8s/data/media/photos/abasit