autoscaling:
  minReplicas: 1
  maxReplicas: 1

securityContext:
  fsGroup: 1337
  runAsGroup: 1337
  runAsNonRoot: true
  runAsUser: 1337
containerSecurityContext:
  capabilities:
    drop:
    - ALL
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true

service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.30.126
  externalTrafficPolicy: "Local"
  type: LoadBalancer
  ports:
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
# affinity:
#   # This podAntiAffinity ensures ingress controllers are not scheduled on the same node
#   podAntiAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#     - labelSelector:
#         matchExpressions:
#         - key: istio
#           operator: In
#           values:
#           - ingressgateway
#       topologyKey: kubernetes.io/hostnam