---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: postgres

resources:
  - db-pvc.yaml

helmCharts:
  - name: postgresql
    releaseName: postgresql
    namespace: iam
    repo: https://charts.bitnami.com/bitnami
    version: 13.1.5
    valuesFile: values.yaml