---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: postgres

resources:
  - db-pvc.yaml

helmCharts:
  - name: postgressql
    releaseName: postgressql
    namespace: iam
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 12.12.10
    valuesFile: values.yaml