apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: iam
stringData:
    postgres-password: ENC[AES256_GCM,data:NCIOlqXAih6TX7VPrCU=,iv:x6DNkoUUveUf3nqOJe25ZmYpEdVi9x9L9FMLcVA+MEk=,tag:cH+6wlZrYb2ZiYnYt3qbrA==,type:str]
    password: ENC[AES256_GCM,data:vcH7LnFcijh2RnUaeOhIq2rkWPXAvvUkmoY=,iv:JJdnxk/ykR0MiIi27xY1Tl5pl5hiw34JBAVrTSRx5vI=,tag:UXFRqSAdsFFz0bT2pUXsrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOY1pSZnZ0RUN3SmRGRkJE
            K2xJUS9rUlBNRCttVEpZS3NpRmtWbmc2UldJCm03ZTBmZDdrbkpRTmJkRnBEbDF0
            c2Y5NUkvWDcyQkY1UkpZMmVSbzYxcTAKLS0tIEZvLy9oUWxTQ1R0N05zbHNaVFBZ
            cFMwMmU2UnhSNklUNHpuNEQydWxGRTQKMJo2hFq/i2GNQEemjQci+EGph7Vg6wY5
            Nmf+rxawUgf3ec1NNVCHV5XTvhmu/zClb3rR6X7Sw7bY51mUvKPh4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-30T06:44:34Z"
    mac: ENC[AES256_GCM,data:91qIj8OXFqZ4b4UGZ9Ab5IMgxo6oTxTXnJ7zvOwC99tESePJaYD2XKn4C1thw//buPrzQDEgoM7qwa7SYN8VT/Z6iGRS2ZHkFnDUy3boYhknc7lu4IUDrQaAhjvEbKl/oGV0wVf53b7zjBMfUAGsT2iEoZaJ3ZcvR9NPGh7Kyo0=,iv:JUlP6OJJRUR04o4qPTMmDfd0SZPchm1HnpMrzk9VblI=,tag:aLVAVW1lSF8WAoR9/I0+Pw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
