global:
  postgresql:
    auth:
      username: keycloak
      database: iam
      existingSecret: postgres-secret
image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: "16.1.0"
primary:
  persistence:
    enabled: true
    existingClaim: postgresql-data
metrics:
  enabled: false
  serviceMonitor:
    enabled: false