global:
  postgresql:
    auth:
      existingSecret: postgres-secret
      #database: "iam"
      secretKeys:
        adminPasswordKey: postgres-password
        userPasswordKey: db-user
        replicationPasswordKey: db-password
        databaseKey: database
image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: "15.4.0"
primary:
  persistence:
    enabled: true
    existingClaim: postgresql-data
metrics:
  enabled: false
  serviceMonitor:
    enabled: false