apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - ns.yaml

helmCharts:
- name: cert-manager
  releaseName: cert-manager
  namespace: cert-manager
  repo: https://charts.jetstack.io
  version: "1.12.2"
  valuesInline:
    installCRDs: true