apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-db-pvc
  namespace: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path