apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: wordpress
spec:
  selector:
    app: mariadb
  ports:
    - name: tcp-3306
      port: 3306
      targetPort: 3306
  type: ClusterIP