apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-apps
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/prod-cluster/observability/argo-apps
    repoURL: https://github.com/abasitt/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true