---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system

resources:
  - ./namespace.yaml

helmCharts:
  - name: istiod
    releaseName: istiod
    namespace: istio-system
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.18.1
    valuesFile: values.yaml