apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./namespace.yaml
- ./base
- ./networking

patchesStrategicMerge:
- overlays/argocd-cm-patch.yaml
- overlays/argocd-cmd-params-patch.yaml
- overlays/argocd-cm-rbac-patch.yaml