apiVersion: v1
kind: Secret
metadata:
  name: kiali-token
  namespace: observability
  annotations:
    kubernetes.io/service-account.name: kiali
type: kubernetes.io/service-account-token

#kubectl get secret kiali-token -n observability -o jsonpath={.data.token} | base64 -d