apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-apps
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    jqPathExpressions:
    - .webhooks[]?.failurePolicy
    kind: ValidatingWebhookConfiguration
  project: default
  source:
    path: kubernetes/apps/core/istio/argo-apps
    repoURL: https://github.com/abasitt/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true