apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-networking
  namespace: argocd
spec:
  destination:
    namespace: istio-ingress
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/clusters/dagobah/argocd/argocd/networking
    repoURL: https://github.com/abasitt/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true