---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./gateway.yaml
- ./certificate-prd.yaml
- ./authorization.yaml

helmCharts:
  - name: cilium
    releaseName: cilium
    namespace: kube-system
    repo: https://helm.cilium.io/
    version: 1.14.0
    valuesFile: values.yaml