apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/dvdsk/k3s/storage/pvc-780b33e9-f8fe-4846-9cc7-9d2195f75a5d_wordpress_wordpress-pvc