---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - virtualservice.yaml

helmCharts:
  - name: jaeger
    releaseName: jaeger
    namespace: observability
    repo: https://jaegertracing.github.io/helm-charts
    version: 0.72.0
    valuesFile: values.yaml