apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
- name: cert-manager
  releaseName: cert-manager
  namespace: kube-system
  repo: https://charts.jetstack.io
  version: "1.11.0"
  valuesInline:
    installCRDs: true

generators:
- ksops-generator.yaml