---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system

helmCharts:
  - name: base
    releaseName: istio-base
    namespace: istio-system
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.19.3
    valuesFile: values.yaml