apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iam-keycloak
  namespace: argocd
spec:
  destination:
    namespace: iam
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/apps/core/iam/keycloak
    repoURL: https://github.com/abasitt/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true