---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: monitoring
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nfs.hv01.home.arpa
    path: /zp_sda_sdb/k8s/data/monitoring/promestack