---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - virtualservice.yaml
  #- kiali-token.yaml

helmCharts:
  - name: kiali-server
    releaseName: kiali-server
    namespace: observability
    repo: https://kiali.org/helm-charts
    version: 1.76.0
    valuesFile: values.yaml