istio_namespace: istio-system
# Required as discussed here https://kiali.io/docs/configuration/p8s-jaeger-grafana/
external_services:
  istio:
    root_namespace: istio-system
  prometheus:
    url: "http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090/"
  tracing:
    # Enabled by default. Kiali will anyway fallback to disabled if
    # Jaeger is unreachable.
    enabled: true
    in_cluster_url: 'http://jaeger-query.observability.svc.cluster.local:16685/jaeger'
    use_grpc: true
    # Public facing URL of Jaeger
    url: 'http://jaeger.dagobah.internal/jaeger'
  grafana:
    enabled: true
    in_cluster_url: 'http://grafana.observability.svc.cluster.local/'
    # Public facing URL of Grafana
    url: 'http://grafana.dagobah.internal/grafana'
# oidc settings
auth:
  openid:
    #name: Keycloak
    client_id: "kiali"
    disable_rbac: true
    issuer_uri: "https://auth.dagobah.abasitt.tech/auth/realms/home-prod"
  strategy: openid