---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: observability
  labels:
    name: prometheus
spec:
  storageClassName: manual
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs.hv01.home.arpa
    path: /zp_sda_sdb/k8s/monitoring/promestack