apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: observability
stringData:
    admin-user: ENC[AES256_GCM,data:IusVX4o=,iv:NjcNQtRH1jmvrNNrMnMSwYej5EWUcuaB8IRM3YYMVMg=,tag:4xcNQa68+mVl9OTv0oIh1g==,type:str]
    admin-password: ENC[AES256_GCM,data:5Xe4zpjAxM+2/hM=,iv:IvgJS8dQw4ANIKbZd7PXk6QMclZpDvPOGP76r3ndV2I=,tag:t+eKipbTkuvbydIf28C4EA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOY1pSZnZ0RUN3SmRGRkJE
            K2xJUS9rUlBNRCttVEpZS3NpRmtWbmc2UldJCm03ZTBmZDdrbkpRTmJkRnBEbDF0
            c2Y5NUkvWDcyQkY1UkpZMmVSbzYxcTAKLS0tIEZvLy9oUWxTQ1R0N05zbHNaVFBZ
            cFMwMmU2UnhSNklUNHpuNEQydWxGRTQKMJo2hFq/i2GNQEemjQci+EGph7Vg6wY5
            Nmf+rxawUgf3ec1NNVCHV5XTvhmu/zClb3rR6X7Sw7bY51mUvKPh4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-17T15:10:04Z"
    mac: ENC[AES256_GCM,data:TrP0y4CqhUnPNYnH8b+Ez9ktpANzC6rJdpgiXclj1il20rDMeNUbzb7Aq/m3gKmaq0a5LWI3HTefwQgDQR4dzMCx2uOx55Uk97i3tcnZDHcXDmnoS/Clqy/xPFaA56ohC3VbEEVIOSvXTYo0SBsagkobf3400ZwOGKEJO4j/ygM=,iv:3nUi3gz/C1OcnpKjvk9/oEoPZQOXEyluvaU061csR7Q=,tag:9JVEmK4BaO4G2b/WhuhHmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
