---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-bat-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 60Gi