---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security

helmCharts:
  - name: vault-secrets-operator
    releaseName: vault-secrets-operator
    namespace: security
    repo: https://github.com/hashicorp/vault-secrets-operator/tree/main/chart
    version: 0.2.0
    valuesFile: values.yaml