---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoprism-app
  namespace: photoprism
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photoprism
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: photoprism
    spec:
      containers:
        - name: photoprism
          image: photoprism/photoprism:latest
          env:
            - name: HOME
              value: /photoprism
            - name: PHOTOPRISM_CACHE_PATH
              value: /assets/cache
            - name: PHOTOPRISM_IMPORT_PATH
              value: /assets/photos/import
            - name: PHOTOPRISM_EXPORT_PATH
              value: /assets/photos/export
            - name: PHOTOPRISM_ORIGINALS_PATH
              value: /assets/photos/originals
            - name: PHOTOPRISM_DARKTABLE_PRESETS
              value: "false"
            - name: PHOTOPRISM_DATABASE_DRIVER
              value: mysql
            - name: PHOTOPRISM_DEBUG
              value: "true"
            - name: PHOTOPRISM_DETECT_NSFW
              value: "false"
            - name: PHOTOPRISM_DISABLE_CHOWN
              value: "false"
            - name: PHOTOPRISM_DISABLE_CLASSIFICATION
              value: "false"
            - name: PHOTOPRISM_DISABLE_FACES
              value: "false"
            - name: PHOTOPRISM_DISABLE_SETTINGS
              value: "false"
            - name: PHOTOPRISM_DISABLE_TENSORFLOW
              value: "false"
            - name: PHOTOPRISM_DISABLE_WEBDAV
              value: "false"
            - name: PHOTOPRISM_EXPERIMENTAL
              value: "false"
            - name: PHOTOPRISM_HTTP_COMPRESSION
              value: gzip
            - name: PHOTOPRISM_ORIGINALS_LIMIT
              value: "5000"
            - name: PHOTOPRISM_PUBLIC
              value: "false"
            - name: PHOTOPRISM_READONLY
              value: "false"
            - name: PHOTOPRISM_SITE_AUTHOR
              value: ""
            - name: PHOTOPRISM_SITE_CAPTION
              value: Browse Your Life
            - name: PHOTOPRISM_SITE_DESCRIPTION
              value: ""
            - name: PHOTOPRISM_SITE_TITLE
              value: PhotoPrism
            - name: PHOTOPRISM_SITE_URL
              value: http://localhost:2342/
            - name: PHOTOPRISM_UPLOAD_NSFW
              value: "true"
            - name: PHOTOPRISM_WORKERS
              value: "4"
          envFrom:
          - secretRef:
              name: photoprism-secrets
              optional: false
          ports:
            - containerPort: 2342
          volumeMounts:
          - mountPath: /assets/photos/originals
            name: photoprism-originals-pvc
            subPath: media/photos
          - mountPath: /assets/cache
            name: photoprism-pvc
            subPath: cache
          - mountPath: /assets/photos/import
            name: photoprism-pvc
            subPath: import
          - mountPath: /assets/photos/export
            name: photoprism-pvc
            subPath: export
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: 2342
          resources:
            requests:
              memory: '32Mi'
              cpu: '1m'
            limits:
              memory: '512Mi'
              cpu: '1000m'
      restartPolicy: Always
      volumes:
        - name: photoprism-originals-pvc
          persistentVolumeClaim:
            claimName: photoprism-originals-pvc
        - name: photoprism-pvc
          persistentVolumeClaim:
            claimName: photoprism-pvc
      