apiVersion: v1
kind: Service
metadata:
  name: wp-mariadb
  namespace: media
spec:
  selector:
    app: wp-mariadb
  ports:
    - name: tcp-3306
      port: 3306
      targetPort: 3306
  type: ClusterIP