apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: photoprism-bat
  namespace: argocd
spec:
  destination:
    namespace: photoprism-bat
    server: https://kubernetes.default.svc
  project: default
  source:
    path: home-prod/photoprism-bat
    repoURL: https://github.com/abasitt/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true