---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml

helmCharts:
  - name: gateway
    releaseName: istio-internalgateway
    namespace: istio-internalgw
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.19.3
    valuesFile: values.yaml

patchesStrategicMerge:
- overlays/service-patch.yaml