apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- apps/01-istio-base
- apps/01-istiod.yaml
- apps/02-istio-ingress.yaml
- apps/03-cert-manager.yaml
- apps/01-metallb.yaml
- argocd
