---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./pv.yaml

helmCharts:
  - name: kube-prometheus-stack
    releaseName: kube-prometheus-stack
    namespace: observability
    repo: https://prometheus-community.github.io/helm-charts
    version: 51.0.3
    valuesFile: values.yaml

components:
- crds