---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: keycloak

resources:
  - certificate-prd.yaml
  - virtualservice.yaml

helmCharts:
  - name: keycloakx
    releaseName: keycloakx
    namespace: iam
    repo: https://codecentric.github.io/helm-charts
    version: 2.3.0
    valuesFile: values.yaml