apiVersion: v1
kind: Secret
metadata:
    name: keycloak-creds
    namespace: iam
stringData:
    kc-user: ENC[AES256_GCM,data:aHvF9jc=,iv:0KNNFwsKlx3JnCVv4XTWhG9QCoio3mf4qoohe3f0Rh0=,tag:OzWR+YAMw+QrAVkRcQ+atA==,type:str]
    kc-password: ENC[AES256_GCM,data:BjyWSsNfCggEb8oJWzg=,iv:uKTKrYCZLk83hiMnHgVEeeYcZO2kLZVncPF8nwXGZuE=,tag:YoU9YET2nVNxSImilFJ2aQ==,type:str]
    #ENC[AES256_GCM,data:nke+FCDJTgPD4TGrbjKA,iv:yBHFOI2g4n8WYVOl+hTQdUbmgnPGOIx326OV5eVBQkQ=,tag:J58KbkMRtuOBgpKUt0h14g==,type:comment]
    username: ENC[AES256_GCM,data:pkXHp2Hf5vc=,iv:WhfiQSR8tEJl8+cInzDnsrRyUUpTOBJCGCAIbRaNFZs=,tag:2vBAdSjZvucYFrwBhlYsZA==,type:str]
    password: ENC[AES256_GCM,data:A5xWZw0CkxF51rERllT9cmQdzQPTtPR/Ndg=,iv:t1AZCaMspgmCxOX9K1nPeyJp/oXETLkDaWO8yCOO9nM=,tag:gWH56ZQpepU8JWESnOj8qg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8pq3mz7lhcnf3ajppkf9ee9j7ywapkenrads9nk3yjm08szd4rqwy3r67
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOY1pSZnZ0RUN3SmRGRkJE
            K2xJUS9rUlBNRCttVEpZS3NpRmtWbmc2UldJCm03ZTBmZDdrbkpRTmJkRnBEbDF0
            c2Y5NUkvWDcyQkY1UkpZMmVSbzYxcTAKLS0tIEZvLy9oUWxTQ1R0N05zbHNaVFBZ
            cFMwMmU2UnhSNklUNHpuNEQydWxGRTQKMJo2hFq/i2GNQEemjQci+EGph7Vg6wY5
            Nmf+rxawUgf3ec1NNVCHV5XTvhmu/zClb3rR6X7Sw7bY51mUvKPh4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-30T04:23:20Z"
    mac: ENC[AES256_GCM,data:yLhdxdX2DJIBl7WRkn2RA7Iypza6HsuG6vHkylGmHVyZ7WV/jZ7fM0LqpsKCQRpiEcqkxBuPAct0X2ioAR250GHMwZ/B542swXOUNyCBrC/KLjpoKVGpKdIRcujhcp+GtZNQrQIsgmcp2EzTh5c8ruThWU6slld+yTI+CFarbM8=,iv:WLY0hkjIHMvKSPsWa7i71VsCiFESev6ZZh5LDjFFqnM=,tag:PswwBndwWnpmp+rWZsLtEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
