---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak-vs
  namespace: iam
spec:
  hosts:
  - "auth.dagobah.abasitt.tech"
  gateways:
  - iam-gateway
  http:
  - name: https-redirect
    match:
      - scheme:
          exact: http
        uri:
          # This is not a perfect regex but RE2 does not allow negations so we have to hack a it
          # Note: this pattern will redirect to HTTPS all URIs NOT starting with `/.well-` (which should be the best case since your business URIs are unlikely to start with that)
          # this to let pass requests to renew certs like `/.well-known/acme-challenge/...`
          regex: "^/(([^\\.].*)|(\\.[^w].*)|(\\.w[^e].*)|(\\.we[^l].*)|(\\.wel[^l].*)|(\\.well[^\\-].*))"
    redirect:
      scheme: https
      redirectCode: 302 # 302 to not mess with risky permanent redirections since a workaround
  - name: auth-redirect
    match:
    - uri:
        exact: /
    redirect:
      uri: /auth 
  - name: "keycloak-routes"
    match:
    - uri:
        prefix: "/auth"
    route:
    - destination:
        host: keycloak-http.iam.svc.cluster.local
        port:
          number: 80
      weight: 100
