---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-books
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs.hv01.home.arpa
    path: /zp_sda_sdb/k8s/data/media/books
