apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-books
  namespace: media
spec:
  accessModes:
      - ReadWriteOnce
  storageClassName: manual
  volumeName: calibre-books
  resources:
      requests:
          storage: 2Gi
