apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-books
  namespace: calibre
spec:
  storageClassName: manual
  capacity:
      storage: 2Gi
  accessModes:
      - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
      path: /mnt/dsk4tb1/k3s/calibre/books