apiVersion: v1
kind: Service
metadata:
  name: ha-service
  namespace: home-assistant
spec:
  selector:
    app: home-assistant
  ports:
    - name: http
      protocol: TCP
      port: 8123
      targetPort: 8123
  type: ClusterIP