---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - virtualservice.yaml

helmCharts:
  - name: grafana
    releaseName: grafana
    namespace: observability
    repo: https://grafana.github.io/helm-charts
    version: 7.0.6
    valuesFile: values.yaml