apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calibre
  namespace: argocd
spec:
  destination:
    namespace: media
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/apps/media/calibre
    repoURL: https://github.com/abasitt/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}